import numpy as np

# Embedding function parameters
nrho = 5000
drho = 15 * 0.1664185884538253E-02
rho = np.arange(0, drho * nrho, drho)
F_pot = -np.sqrt(rho)

arr_fs = []

# Tabulate F_pot
for jj in range(1000):
    ii = slice(5 * jj, 5 * (jj + 1))
    arr_fs.append(F_pot[ii])

# Electron density parameters
A = 2.591061
d = 4.076980
rend = 5

nr = 5000
dr = rend / (nr - 1)
rr = np.arange(0, rend + dr, dr)

rho_pot = []

# Compute rho_pot
for r in rr:
    if r < d:
        rho = A ** 2 * (r - d) ** 2
    else:
        rho = 0
    rho_pot.append(rho)

# Tabulate rho_pot
for jj in range(1000):
    ii = slice(5 * jj, 5 * (jj + 1))
    arr_fs.append(rho_pot[ii])

# Pair-potential parameters
c = 4.20
# c0 = 1.2157373
c0 = 1.214807674
# c1 = 0.0471471
c1 = 0.02701390201
c2 = -0.1217350
c3 = 0
c4 = 0

V_pair = []

# Compute pair potential
for r in rr:
    if r < c:
        V = (r - c) ** 2 * (c0 + c1 * r + c2 * r ** 2 + c3 * r ** 3 + c4 * r ** 4)
    else:
        V = 0
    V_pair.append(V)

pair_pot = np.array(V_pair) * rr

# Tabulate pair potential
for jj in range(1000):
    ii = slice(5 * jj, 5 * (jj + 1))
    arr_fs.append(pair_pot[ii])

# Write to new data file
data_out_file_name = 'Ta_orig_FS.eam1.alloy'
with open(data_out_file_name, 'w') as data_out_file_ID:
    dataArray = [
        'Ta2 EAM/FS model',
        'Original finnis and sinclair parameters',
        'Generated by python',
        '1  Ta',
        '5000  2.4962788268074E-02  5000  10.00200040008e-04  0.4200000E+01',
        '73     180.95         3.304    bcc'
    ]

    # Rewrite the first 6 lines
    for line in dataArray:
        data_out_file_ID.write(line + '\n')

    # Write tabulated data
    for k in range(3000):
        data = arr_fs[k]
        str_data = ' '.join(map(str, data))
        data_out_file_ID.write(str_data + '\n')
